In [150]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split,cross_val_score

In [151]:
df=pd.read_csv("forestfires.csv")

In [152]:
df.head()

month  day  FFMC   DMC     DC  ...  monthmay  monthnov  monthoct  monthsep  size_category
0   mar  fri  86.2  26.2   94.3  ...         0         0         0         0          small
1   oct  tue  90.6  35.4  669.1  ...         0         0         1         0          small
2   oct  sat  90.6  43.7  686.9  ...         0         0         1         0          small
3   mar  fri  91.7  33.3   77.5  ...         0         0         0         0          small
4   mar  sun  89.3  51.3  102.2  ...         0         0         0         0          small

[5 rows x 31 columns]

In [153]:
df.drop(['month','day'],axis=1,inplace=True)

In [154]:
array=df.values

In [155]:
array

array([[86.2, 26.2, 94.3, ..., 0, 0, 'small'],
       [90.6, 35.4, 669.1, ..., 1, 0, 'small'],
       [90.6, 43.7, 686.9, ..., 1, 0, 'small'],
       ...,
       [81.6, 56.7, 665.6, ..., 0, 0, 'large'],
       [94.4, 146.0, 614.7, ..., 0, 0, 'small'],
       [79.5, 3.0, 106.7, ..., 0, 0, 'small']], dtype=object)

In [156]:
X=array[:,:-1]
Y=array[:,-1]


In [157]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [158]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((361, 28), (156, 28), (361,), (156,))

In [159]:
clf = SVC()
param_grid = [{'kernel':['linear','rbf','polynomial'],'gamma':[0.5,0.1,0.01],'C':[10,0.1,0.01] }]
gsv = RandomizedSearchCV(clf,param_grid,cv=6,)
gsv.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
24 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
24 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py", line 180, in fit
    self._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param

RandomizedSearchCV(cv=6, estimator=SVC(),
                   param_distributions=[{'C': [10, 0.1, 0.01],
                                         'gamma': [0.5, 0.1, 0.01],
                                         'kernel': ['linear', 'rbf',
                                                    'polynomial']}])

In [160]:
gsv.best_params_,gsv.best_score_

({'kernel': 'linear', 'gamma': 0.01, 'C': 10}, 0.9806010928961749)

In [161]:
clf=SVC(kernel='linear',C=10)
clf.fit(X_train,Y_train)
y_pred=clf.predict(X_test)
acc=accuracy_score(Y_test,y_pred)*100
print("accuracy =",acc)
confusion_matrix(Y_test,y_pred)

accuracy = 98.71794871794873


array([[ 44,   2],
       [  0, 110]])

In [162]:
confusion_matrix(Y_test,y_pred)

array([[ 44,   2],
       [  0, 110]])

In [163]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

       large       1.00      0.96      0.98        46
       small       0.98      1.00      0.99       110

    accuracy                           0.99       156
   macro avg       0.99      0.98      0.98       156
weighted avg       0.99      0.99      0.99       156

